[package]
name = "lab16_core"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { workspace = true }
unicode-segmentation = {workspace = true}
hashbrown = { workspace = true }
anyhow = { workspace = true }
llama-cpp-2 = { workspace = true }
llama-cpp-sys-2 = { workspace = true }
hf-hub = { workspace = true}
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
fb2 =  { workspace = true }
whatlang = { workspace = true }